export const outcomeTrackingData = {
  measureCategories: [
    {
      categoryId: "outcome_metrics",
      categoryName: "Outcome Metrics",
      categoryType: "primary",
      description: "Primary clinical and operational outcome measures",
      measures: [
        {
          domain: "quality_economic_outcomes",
          domainName: "Quality & Economic Outcomes",
          metrics: [
            {
              metricId: "QEO-001",
              metricName: "Overall Risk Reduction",
              description: "Percentage reduction in overall health risk from baseline",
              dataType: "percentage",
              measurementUnit: "%",
              measurementFrequency: "quarterly",
            },
            {
              metricId: "QEO-002",
              metricName: "Improved Functional Capacity",
              description: "Improvement in patient functional capacity measures",
              dataType: "score",
              measurementUnit: "functional_capacity_score",
              measurementFrequency: "monthly",
            },
            {
              metricId: "QEO-003",
              metricName: "Reduction in Hospitalizations",
              description: "Percentage reduction in hospital admissions",
              dataType: "percentage",
              measurementUnit: "%",
              measurementFrequency: "quarterly",
            },
            {
              metricId: "QEO-004",
              metricName: "Reduction in Emergency Department Visits",
              description: "Percentage reduction in ED visits",
              dataType: "percentage",
              measurementUnit: "%",
              measurementFrequency: "quarterly",
            },
          ],
        },
        {
          domain: "substance_use_cessation",
          domainName: "Substance Use Cessation",
          metrics: [
            {
              metricId: "SUC-001",
              metricName: "Sustained Abstinence Achievement",
              description: "Achievement and maintenance of abstinence for 6 months",
              dataType: "boolean",
              measurementUnit: "achieved/not_achieved",
              measurementFrequency: "monthly",
            },
          ],
        },
        {
          domain: "patient_engagement",
          domainName: "Patient Engagement",
          metrics: [
            {
              metricId: "PE-001",
              metricName: "Self-Monitoring Adherence",
              description: "Patient adherence to self-monitoring protocols",
              dataType: "percentage",
              measurementUnit: "%",
              measurementFrequency: "weekly",
            },
            {
              metricId: "PE-002",
              metricName: "NS Assessment Completion Rate",
              description: "Timely completion of nursing/clinical assessments",
              dataType: "percentage",
              measurementUnit: "%",
              measurementFrequency: "weekly",
            },
            {
              metricId: "PE-003",
              metricName: "Patient Confidence & Personal Agency",
              description: "Patient self-efficacy and agency measurement",
              dataType: "score",
              measurementUnit: "scale_0_10",
              measurementFrequency: "monthly",
            },
            {
              metricId: "PE-004",
              metricName: "Goal Achievement Rate",
              description: "Percentage of patient-set goals achieved",
              dataType: "percentage",
              measurementUnit: "%",
              measurementFrequency: "monthly",
            },
            {
              metricId: "PE-005",
              metricName: "Progress Toward Goals",
              description: "Incremental progress tracking toward goals",
              dataType: "percentage",
              measurementUnit: "%",
              measurementFrequency: "weekly",
            },
          ],
        },
        {
          domain: "resource_utilization",
          domainName: "Resource Enrollment & Completion",
          metrics: [
            {
              metricId: "RU-001",
              metricName: "Resource Completion Rate",
              description: "Percentage of identified resources completed by patient",
              dataType: "percentage",
              measurementUnit: "%",
              measurementFrequency: "monthly",
            },
          ],
        },
        {
          domain: "patient_satisfaction",
          domainName: "Patient Satisfaction and Trust",
          metrics: [
            {
              metricId: "PS-001",
              metricName: "Satisfaction Score Improvement",
              description: "Change in patient satisfaction from baseline",
              dataType: "score_delta",
              measurementUnit: "points",
              measurementFrequency: "quarterly",
            },
          ],
        },
        {
          domain: "safety_outcomes",
          domainName: "Safety Outcomes",
          metrics: [
            {
              metricId: "SO-001",
              metricName: "Medication Error Rate",
              description: "Incidence of medication errors per patient",
              dataType: "rate",
              measurementUnit: "errors_per_1000_patient_days",
              measurementFrequency: "monthly",
            },
            {
              metricId: "SO-002",
              metricName: "Fall Reduction Rate",
              description: "Reduction in patient falls from baseline",
              dataType: "percentage",
              measurementUnit: "%",
              measurementFrequency: "monthly",
            },
          ],
        },
      ],
    },
    {
      categoryId: "personalized_report_metrics",
      categoryName: "Personalized Report Metrics",
      categoryType: "analytical",
      description: "Advanced analytics and predictive metrics for personalized patient reporting",
      measures: [
        {
          domain: "personalized_metrics",
          domainName: "Comprehensive Health Profile",
          metrics: [
            {
              metricId: "PR-001",
              metricName: "Risk Profile Analysis",
              description: "Comprehensive analysis of patient risk factors",
              dataType: "composite",
              measurementUnit: "categorical",
              updateFrequency: "monthly",
            },
            {
              metricId: "PR-002",
              metricName: "Overall Risk Status",
              description: "Composite risk scoring for readmission and ED visits",
              dataType: "composite_score",
              measurementUnit: "risk_level",
              updateFrequency: "real-time",
            },
            {
              metricId: "PR-003",
              metricName: "Resource Utilization Assessment",
              description: "Analysis of healthcare resource utilization patterns",
              dataType: "categorical",
              measurementUnit: "utilization_category",
              updateFrequency: "monthly",
            },
            {
              metricId: "PR-004",
              metricName: "Cost Impact Analysis",
              description: "Estimated and predicted cost with health impact",
              dataType: "composite",
              measurementUnit: "USD",
              updateFrequency: "monthly",
            },
            {
              metricId: "PR-006",
              metricName: "Medication Adherence Score",
              description: "Composite medication adherence measurement",
              dataType: "percentage",
              measurementUnit: "%",
              updateFrequency: "monthly",
            },
            {
              metricId: "PR-007",
              metricName: "Mental Health Score",
              description: "Mental health status and determining factors",
              dataType: "composite",
              measurementUnit: "scale_0_100",
              updateFrequency: "monthly",
            },
            {
              metricId: "PR-008",
              metricName: "Physical and Social Wellbeing",
              description: "Holistic wellbeing assessment",
              dataType: "composite",
              measurementUnit: "scale_0_100",
              updateFrequency: "quarterly",
            },
            {
              metricId: "PR-010",
              metricName: "Health Engagement Score",
              description: "Overall patient engagement in health activities",
              dataType: "score",
              measurementUnit: "scale_0_100",
              updateFrequency: "weekly",
            },
            {
              metricId: "PR-011",
              metricName: "Digital Health Literacy",
              description: "Patient's ability to use digital health tools",
              dataType: "score",
              measurementUnit: "scale_0_100",
              updateFrequency: "semi-annually",
            },
            {
              metricId: "PR-013",
              metricName: "SDOH Index Score",
              description: "Social Determinants of Health composite score",
              dataType: "composite_score",
              measurementUnit: "scale_0_100",
              updateFrequency: "quarterly",
            },
            {
              metricId: "PR-014",
              metricName: "Behavioral Health Determinant Segment",
              description: "Patient segmentation based on behavioral health factors",
              dataType: "categorical",
              measurementUnit: "segment_label",
              updateFrequency: "monthly",
            },
            {
              metricId: "PR-015",
              metricName: "Overall Health Index Score",
              description: "Comprehensive health status composite score",
              dataType: "composite_score",
              measurementUnit: "scale_0_100",
              updateFrequency: "monthly",
            },
          ],
        },
      ],
    },
  ],
}
